### ISSUE TITLE
The paper stated that D=9 while here the input features are 7 only

### ISSUE THREAD

**Issue by ma7555** [tyagi-iiitv/PointPillars#18]
I think you divided the 9 features into 7 (point features) and 3 (not 2) for indexes in order to map them back to pillars indicies 

is that correct?

Also, how are the 12000 (max_pillars)  resulted into a 504x504 pillars grid? that results in 254,016 pillars.

**Comment by nschein** [comment]
max_pillars is the maximum number of filled cells in the pillar grid, i.e., you will have at least 504x504-12000 empty pillars, see PointPillars paper.

Also, the 3 indices for ordering back are simply there an implementation detail. The third index is used (and filled) in network.py despite it is created in the cpp file to indicate the corresponding batch.

As for the 7 instead of 9 features, you might be on to something. It is not obvious to me, whether this is accurate or not.

**Comment by tjtanaa** [comment]
From the papers, the features of the points in the (D, P, N, B) pillars are [x, y, z, intensity, xc, yc, zc, xp, yp]. 

The implementation that this repository uses [dx, dy, dz, intensity, xc, yc, zc] as the features of the points in the pillars. This is different from the original paper.
